### ISSUE TITLE
Replicate returns a base64 encoded image and this node tries to make a GET request with it.

### ISSUE THREAD

**Issue by Sidd065** [replicate/comfyui-replicate#11]
I am using the Clarity Upscaler node and getting this error. 
![image](https://github.com/user-attachments/assets/57463190-779d-4a4a-bce4-ec58563556fb)

I think issue might be caused by this change in Replicate's python library https://replicate.com/docs/topics/predictions/output-files#fileoutput-objects
```[tasklist]
### Tasks
```

**Comment by fofr** [comment]
This should be fixed now
