### ISSUE TITLE
Direct installation not working

### ISSUE THREAD

**Issue by gaduffl** [replicate/comfyui-replicate#5]
I followed the direct installation steps, but it seems that the nodes were not installed correctly.
(Win10).
![image](https://github.com/user-attachments/assets/b92c91be-587d-4a94-9780-c431ecc2ad7e)

**Comment by formulake** [comment]
Yup, I'm unable to find these nodes in the node menu as well. Would appreciate any help from those who've made it work.

**Comment by gaduffl** [comment]
Claude was so nice to help me out here, the python replicate module has to be installed first!

Open a command prompt or terminal.
Navigate to your ComfyUI directory. Based on your error message, it should be:
CopyD:\Code\ComfyUI_windows_portable\ComfyUI

Activate the Python environment that ComfyUI is using. If you're using the portable version, there should be a script to activate the environment. Look for something like python_embeded\python.exe or a similar activation script.
Once the environment is activated, install the 'replicate' module using pip:
Copypip install replicate

After the installation is complete, try running ComfyUI again.
