### ISSUE TITLE
Unknown node type "DF_Text_Box" from Flux.json

### ISSUE THREAD

**Issue by janrvdolf** [replicate/comfyui-replicate#6]
Hi, 

tried to install on Mac and have the following error - unknown node type "DF_Text_Box"

<img width="1863" alt="Screenshot 2024-08-09 at 11 44 49" src="https://github.com/user-attachments/assets/069f5c98-f8f1-45c8-88ec-6f464260b227">

How to fix it?

**Comment by fofr** [comment]
That node comes from:
https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes

**Comment by janrvdolf** [comment]
Installed it into `custom_nodes` and it works. Thank you!
