### ISSUE TITLE
please how install API TOKEN on Mac 

### ISSUE THREAD

**Issue by stef06** [replicate/comfyui-replicate#9]
i am sorry i don't understand how I can install API TOKEN on Mac M1 I don't understand please explain me with détail ??

**Comment by dihan** [comment]
Havent tested but this would work

https://github.com/replicate/comfyui-replicate/issues/7

**Comment by fofr** [comment]
On MacOS or Linux:

```sh
export REPLICATE_API_TOKEN="r8_************"; python main.py
```
